//! Actor stub — compiled to wasm32-wasip2 via `wash build`.
//!
//! `cargo check --target wasm32-wasip2` does NOT work for actor crates without
//! vendored WIT deps. Use `wash build --project-path actors/<name>` instead.
//! The CI `build-actors` job handles this correctly.
//!
//! Implementation lives in this file once WIT bindings are generated by wash.

// Only compile the full implementation when the wasm component model is active
// (i.e. when `wash build` drives compilation with WASM_COMPONENT_MODEL env set
// or similar). For plain `cargo check` this crate is a valid empty lib.
